[package]
name = "wasm-plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindings = {path = "../bindings/rust-plugin"}

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]